export const shortFilms = [
    {
        name: 'The chair',
        duration: 24,
        director: 'Curry Barker',
        writer: 'Curry Barker',
        producer: "Adlih Torres, Anthony Pavone and Curry Barker",
        cast: ['Anthony Pavone', 'Haley Schwartz', 'David Alan Graf'],
        year: 2023,
        cover: 'https://s1.dmcdn.net/v/V3Ok-1adrVVlAJEIy/x1080',
        url: 'https://www.youtube.com/embed/mhazCS14Tas',
        synopsis: "After Reese (Anthony Pavone) brings home an antique chair, a series of horrific events follow, leading him to question if it's a malevolent spirit the chair possesses or the darkness inside his own mind."
    },
    {
        name: 'THE SOUND',
        duration: 11,
        director: 'Patrick Stagg',
        writer: 'Patrick Stagg',
        producer: "Patrick Stagg",
        cast: ['Marcus Klein'],
        year: 2021,
        cover: 'https://i.ytimg.com/vi/Q4WljvdXfFc/maxresdefault.jpg',
        url: 'https://www.youtube.com/embed/Q4WljvdXfFc',
        synopsis: "A modern re-telling of an old classic from Edgar Allan Poe.  A strange noise torments a man who’s isolated within his small countryside home."
    },
    {
        name: 'While mortals sleep',
        duration: 13,
        director: 'Alex Fofonoff',
        writer: 'Alex Fofonoff',
        producer: "Matthew James Reilly",
        cast: ['Carie Kawa', 'Will Brill', 'Grace Morrison', 'Ron Binion'],
        year: 2024,
        cover: 'https://directorsnotes.com/wp-content/uploads/2023/01/while_mortals_sleep_04.jpg',
        url: 'https://www.youtube.com/embed/vvM_AkK2Va8',
        synopsis: "When a cold case novelist's career implodes, she seeks refuge in her friend's remote vacation home. Upon arrival, she encounters a strange couple who claim to be the caretakers. As tensions build, a dark secret begins to emerge."
    },
    {
        name: 'Skin deep',
        duration: 11,
        director: 'Abby Alleyne Brooke',
        writer: 'Abby Alleyne Brooke',
        producer: "Henry Sheeran and Abby Alleyne Brooke",
        cast: ['Lilian Bornstein', 'Henry Sheeran', 'Natalie Shinnick'],
        year: 2024,
        cover: 'https://i.ytimg.com/vi/TVEOwcI95Ms/sddefault.jpg',
        url: 'https://www.youtube.com/embed/TVEOwcI95Ms',
        synopsis: "On the last night of summer in a quiet coastal town, an insecure young woman finally reveals to her crush exactly how she feels... and who she is."
    },
    {
        name: 'THE JOGGER',
        duration: 7,
        director: 'Daryl Denner',
        writer: 'Daryl Denner',
        producer: "Daryl Denner",
        cast: ['Amanda Troisi', 'Michael Bollentin'],
        year: 2021,
        cover: 'https://i.ytimg.com/vi/17a_UGQGls4/maxresdefault.jpg',
        url: 'https://www.youtube.com/embed/17a_UGQGls4',
        synopsis: "Out for her morning jog, a woman runs for her life after being pursued by a mysterious man."
    },
    {
        name: 'THE THING IN THE APARTMENT ',
        duration: 10,
        director: 'John William Ross',
        writer: 'John William Ross',
        producer: "Jonathan Judelson",
        cast: ['Melia Renee', 'Carly Jones', 'Ryan Allan Young'],
        year: 2024,
        cover: 'https://www.blog.thefilmfund.co/wp-content/uploads/2023/01/the-thing-in-the-apartment-1024x576.jpg',
        url: 'https://www.youtube.com/embed/vFsRbkwZRu0',
        synopsis: "There's something in Lindsay's apartment..."
    },
    {
        name: 'DISGUISE',
        duration: 10,
        director: 'Tyler Czajkowski',
        writer: '',
        producer: "Zoe Rose LoMenzo & Tyler Czajkowski",
        cast: ['Zoe Rose LoMenzo'],
        year: 2022,
        cover: 'https://i.ytimg.com/vi/zlpfcKffgDA/maxresdefault.jpg',
        url: 'https://www.youtube.com/embed/zlpfcKffgDA',
        synopsis: "Based on the short story, 'The Ultimate Disguise' from Reddit NoSleep."
    },
    {
        name: 'INFERNO',
        duration: 6,
        director: 'Bishal Dutta',
        writer: 'Bishal Dutta',
        producer: "Ashim Ahuja",
        cast: ['Taylor Cloyes', 'Craig NJ'],
        year: 2020,
        cover: 'https://i.ytimg.com/vi/vvM_AkK2Va8/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDiewKT4WHk-nVYHuK1YKtiwFw57A',
        url: 'https://www.youtube.com/embed/x2c39v5NMj4',
        synopsis: "Trapped in a nightmarish motel, an exhausted woman uses the last of her energy to make a desperate escape attempt from the monster chasing her."
    },
    {
        name: 'Halfway',
        duration: 10,
        director: 'Mahesh Pattambi',
        writer: 'Mahesh Pattambi',
        producer: "Mahesh Pattambi",
        cast: ['Rajesh Raj', 'Kabir Avran', 'Baby Dhakshina Soorya', 'Sreelakshmy Mohandas', 'Shereen Saidu Mohammed', 'Noushad Kabu', 'Satheesh Thanoor'],
        year: 2022,
        cover: 'https://i.ytimg.com/vi/H7F04vbKbXc/hqdefault.jpg',
        url: 'https://www.youtube.com/embed/H7F04vbKbXc',
        synopsis: "John is traveling on a lonely highway to celebrate the weekend in his friend's home. Unexpected events happen along the way leading John astray."
    },
    {
        name: 'RUN!',
        duration: 1,
        director: '',
        writer: '',
        producer: "",
        cast: [],
        year: 2015,
        cover: 'https://i.ytimg.com/vi/we2YF1J6jxg/maxresdefault.jpg',
        url: 'https://www.youtube.com/embed/we2YF1J6jxg',
        synopsis: "Run and don´t look behind you!"
    },
    {
        name: 'Knock Knock',
        duration: 4,
        director: ' Alex Magaña',
        writer: ' Alex Magaña',
        producer: " Alex Magaña",
        cast: ['Becca Buckalew', 'Willow Grey', 'Alex Magaña', 'Elena Hollander', 'Samuel Code'],
        year: 2021,
        cover: 'https://i.ytimg.com/vi/dwDIz2YNQSo/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCmeIlzsbtn6PawsKYYAiXmm_1JzQ',
        url: 'https://www.youtube.com/embed/dwDIz2YNQSo',
        synopsis: "A woman hears a loud knock knock coming from the hotel room next to hers..."
    },
    {
        name: 'Other Side of the Box',
        duration: 15,
        director: 'Caleb J. Phillips',
        writer: 'Caleb J. Phillips and Nick Tag',
        producer: "Nick Coppola, Caleb J. Phillips and Nick Tag",
        cast: ['Tyler Pochop', 'Teagan Rose', 'Josh Schell', 'Nick Tag'],
        year: 2020,
        cover: 'https://i.ytimg.com/vi/OrOYvVf6tIM/maxresdefault.jpg',
        url: 'https://www.youtube.com/embed/TGZg1YqXv9o',
        synopsis: "A couple receives a mysterious package from an old friend."
    },
    {
        name: 'The Girl in the Woods',
        duration: 6,
        director: 'Laura Kulik',
        writer: 'Laura Kulik',
        producer: "Laura Kulik and Logan Fulton",
        cast: ['Nicole Outman'],
        year: 2020,
        cover: 'https://i.ytimg.com/vi/xNlHKiX0R_4/maxresdefault.jpg',
        url: 'https://www.youtube.com/embed/xNlHKiX0R_4',
        synopsis: "After a woman gets into a car accident on an isolated forest road, she follows a trail of blood into the woods and sees something more horrifying than she could ever imagine. "
    },
    {
        name: 'WARNINGS',
        duration: 19,
        director: 'Curry Barker',
        writer: 'Curry Barker',
        producer: "Cooper Tomlinson",
        cast: ['Haley Fitzgerald', 'Curry Barker', 'Cooper Tomlinson', 'Riley Barker', 'Malcolm Kelner'],
        year: 2022,
        cover: 'https://i.ytimg.com/vi/Hik4n3Ld88Y/maxresdefault.jpg',
        url: 'https://www.youtube.com/embed/Hik4n3Ld88Y',
        synopsis: "When Sean (Curry Barker) finds a mysterious note on his car, he questions where it came from, and why strange things are beginning to happen..."
    },
    {
        name: 'The Dinner After',
        duration: 12,
        director: 'Matty Crawford',
        writer: 'Paul Carey ',
        producer: "Thijme Grol",
        cast: ['Lucy Doyle', 'Joanna Brookes', 'John Ramm', 'Fern Deacon'],
        year: 2023,
        cover: 'https://i.ytimg.com/vi/-PZqZ4O4IBs/maxresdefault.jpg',
        url: 'https://www.youtube.com/embed/-PZqZ4O4IBs',
        synopsis: "A guilt-stricken Angela, visits her parents for what at first seems to be a routine family dinner, only for a painful truth to bubble to the surface, descending the evening into a nightmare. "
    },
    {
        name: 'THE TUNNEL',
        duration: 5,
        director: 'Alex Spear & Andrew Clabaugh',
        writer: 'Andrew Clabaugh',
        producer: "Alex Spear, Andrew Clabaugh, & Jordan Frechtman ",
        cast: ['Jordan Frechtman', 'Andrew Clabaugh'],
        year: 2022,
        cover: 'https://i.ytimg.com/vi/HCJsbp1N_kQ/maxresdefault.jpg',
        url: 'https://www.youtube.com/embed/HCJsbp1N_kQ',
        synopsis: "A man walks through a seemingly mundane tunnel."
    },
    {
        name: 'STALLED',
        duration: 19,
        director: 'Matt Black',
        writer: 'Matt Black',
        producer: "Ryan Polly",
        cast: ['Jacob Daniels'],
        year: 2022,
        cover: 'https://i.ytimg.com/vi/7mSH86O2qzA/maxresdefault.jpg',
        url: 'https://www.youtube.com/embed/7mSH86O2qzA',
        synopsis: "A man is trapped in a time paradox."
    },
    {
        name: 'Timothy',
        duration: 8,
        director: 'Marc Martínez Jordán',
        writer: 'Marc Martínez Jordán',
        producer: "Arnau Pons",
        cast: ['Roger Moreno', 'Ann. M. Perelló', 'Hodei del Barrio'],
        year: 2020,
        cover: 'https://www.thegate.ca/wp-content/uploads/2016/10/Minutes-Past-Midnight.jpg',
        url: 'https://www.youtube.com/embed/IcnBB5p3JIM',
        synopsis: " Simon is a little boy that has to deal with his babysitter, Sonia, a total nuisance. But that same night Simon will receive and unexpected visitor, Timothy, the main character of Simon's favourite show, a visit he will never forget."
    },
    {
        name: 'This must be the place',
        duration: 8,
        director: 'Merlin Camozzi ',
        writer: 'Merlin Camozzi ',
        producer: "Merlin Camozzi",
        cast: ['Sarah Lyddan', 'Lila Gavares', 'Brigid Abreu', 'Laura Louise Richardson', 'Annette Bizal'],
        year: 2021,
        cover: 'https://static1.squarespace.com/static/5fdc5b929732840ea86243a3/t/605865be39ac75765fe4f3dd/1616405954894/this+must+be+the+place+1.jpg?format=1500w',
        url: 'https://www.youtube.com/embed/i1gQLBXwmYw',
        synopsis: "When she seeks to join a group of low-end urban witches, Bonnie must decide how far she's willing to go in order to learn their craft, and find a home."
    },
    {
        name: 'Bus stop',
        duration: 13,
        director: 'Zora Cielle Anri',
        writer: 'Zora Cielle Anri',
        producer: "Iván Veselov",
        cast: ['Joshua Shea', 'Poppie Boyes', 'Mike Kelson', 'Olivia Post'],
        year: 2023,
        cover: 'https://horrorandsons.com/wp-content/uploads/2023/07/girl-pic.jpg',
        url: 'https://www.youtube.com/embed/fz0j2lAo4K0',
        synopsis: "A chilling horror short film about two strangers waiting for the bus, who become entangled in the mysterious and terrifying circumstances surrounding the bus stop."
    },
    {
        name: 'Box fort',
        duration: 15,
        director: 'Tyler Czajkowski',
        writer: 'Based on the short story by Mallory Eddy',
        producer: "Bianca Crespo, Ian Abell & Zach Strouse",
        cast: ['Christy Czajkowski', 'Ally Ibach', 'Maggie Flynn'],
        year: 2020,
        cover: 'https://m.media-amazon.com/images/M/MV5BMTA5NmM2NDctYzUxOS00NmU4LTlkYzktYmM5YzdlMmVhNTIxXkEyXkFqcGdeQXVyOTc5OTQ5ODY@._V1_.jpg',
        url: 'https://www.youtube.com/embed/muVUgm6ICiE&t=15s',
        synopsis: "One weekend while their parents are away, three sisters decide to build a box fort. As strange things start to happen around them, they wonder if someone or someTHING is living inside of it."
    },
    {
        name: 'Tunnel',
        duration: 7,
        director: 'Sean Louis Kelly',
        writer: 'Spencer Fappiano',
        producer: "",
        cast: ['Spencer Fappiano', 'Sean Louis Kelly'],
        year: 2021,
        cover: 'https://s1.dmcdn.net/v/V3fSU1aeYDOVe51AK/x1080',
        url: 'https://www.youtube.com/embed/XYLgwxbwEb8',
        synopsis: "A nature photographer discovers an old railway tunnel that holds a strange mystery..."
    },
    {
        name: 'Stay up late',
        duration: 4,
        director: 'My An',
        writer: 'My An',
        producer: "Grisfox Studio",
        cast: [],
        year: 2021,
        cover: 'https://i.ytimg.com/vi/f459r-4eS8U/maxresdefault.jpg',
        url: 'https://www.youtube.com/embed/f459r-4eS8U',
        synopsis: "She wasn't sure what she was looking at."
    },
    {
        name: 'On my way',
        duration: 7,
        director: 'Colin Krawchuck',
        writer: 'Colin Krawchuck',
        producer: "Colin Krawchuck",
        cast: ['Colin Krawchuck', 'Benjamin Royer', 'Nick Lewis'],
        year: 2016,
        cover: 'https://m.media-amazon.com/images/M/MV5BODlkOTY4ZDMtNmMwYy00OTU1LThkYzMtZTk2MTE1YzcwMTRiXkEyXkFqcGc@._V1_.jpg',
        url: 'https://www.youtube.com/embed/EpL5TXROpZ8',
        synopsis: "While on his way to a Halloween party, a man drives through a town, slowly realizing it's gone insane."
    },
    {
        name: 'How to Stay Healthy',
        duration: 7,
        director: 'Aze Alter',
        writer: 'Aze Alter',
        producer: "Aze Alter",
        cast: ['Aze Alter'],
        year: 2024,
        cover: 'https://d1735p3aqhycef.cloudfront.net/topview_blog/thumbnail_b19574121ce54647f643b9785ee8f4d9.jpg',
        url: 'https://www.youtube.com/embed/e2RT79khjvI',
        synopsis: "Here at the Capitol, we offer 2 easy options to stay healthy!"
    },
    {
        name: 'Haunting memories',
        duration: 4,
        director: 'No info',
        writer: '',
        producer: "",
        cast: [''],
        year: 2024,
        cover: 'https://i.ytimg.com/vi/NBVIUurHMFE/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAXaKk_C-h8n5Ar3XTNADGyRvJMsg',
        url: 'https://www.youtube.com/embed/NBVIUurHMFE',
        synopsis: "Have you ever been haunted by disturbing memories? Here is your chance…"
    },
    {
        name: 'MORA',
        duration: 12,
        director: 'Sam Evenson',
        writer: 'Sam Evenson',
        producer: "Victoria Fratz",
        cast: ['Tim Torre', 'Jamie Taylor Ballesta', 'Valeska Miller'],
        year: 2024,
        cover: 'https://i0.wp.com/www.horrorguys.com/wp-content/uploads/2024/08/Screenshot-2024-07-28-at-7.02.12%E2%80%AFPM.png?fit=1302%2C718&ssl=1',
        url: 'https://www.youtube.com/embed/mUXpTAdu_8U',
        synopsis: "A struggling artist searches for a mysterious woman that shows up in gruesome AI-generated images."
    },
    {
        name: 'Another',
        duration: 4,
        director: 'Dave Clark',
        writer: 'Dave Clark',
        producer: "Dave Clark",
        cast: ['Melissa Browne', 'Diana Levan', 'Colleen Rourke'],
        year: 2024,
        cover: 'https://m.media-amazon.com/images/M/MV5BMGRmZDI4NDEtNzlhMC00ODNlLTk3YTAtMWJkNjM5NGViZDY1XkEyXkFqcGc@._V1_.jpg',
        url: 'https://www.youtube.com/embed/vyeZn4Xks8E',
        synopsis: "This project was a combination of live-action footage with AI-generated VFX"
    },
    {
        name: 'AI Artist',
        duration: 9,
        director: 'Dani Barker',
        writer: 'Dani Barker',
        producer: "Dani Barker",
        cast: ['Dani Barker', 'Azriel Dalman', 'Jeesey Nelson'],
        year: 2023,
        cover: 'https://m.media-amazon.com/images/M/MV5BYzYxOTZlYmItNWI3MC00NTA2LTk3YzMtZTY4OTM4ZTdiZmQwXkEyXkFqcGc@._V1_.jpg',
        url: 'https://www.youtube.com/embed/xcNSL7mwUGY',
        synopsis: "After a shrimp-fingered hermit discovers a passion for AI Art, his compulsion to create monsters bleeds far beyond his computer screen."
    },
    {
        name: 'MAKR',
        duration: 13,
        director: 'Hana Kazim',
        writer: 'Faris Kazim and Hana Kazim',
        producer: "Hind Al Basti",
        cast: ['Reiley Cook'],
        year: 2024,
        cover: 'https://horrorghouls.com/wp-content/uploads/2020/03/makr-short-horror-movie-768x432.jpg',
        url: 'https://www.youtube.com/embed/qIOd-fQuiig',
        synopsis: "A fake exorcist visits the home of a man who thinks his wife is possessed by a Djinn, only to find out that things are not as they seem."
    },
    {
        name: 'Alexia',
        duration: 8,
        director: 'ANDRÉS BORGHI',
        writer: 'ANDRÉS BORGHI',
        producer: "ANDRÉS BORGHI",
        cast: ['SERGIO BERÓN', 'PAULA CARRUEGA', 'PILAR BOYLE'],
        year: 2013,
        cover: 'https://img.unocero.com/2015/02/alexiaporta.jpg',
        url: 'https://www.youtube.com/embed/sV8UnfFmD-Y&t=1s',
        synopsis: "A man haunted by his ex-girlfriend's suicide. On the anniversary of her death, strange things happen when her social media account starts sending eerie notifications."
    },
    {
        name: 'The black hole',
        duration: 2,
        director: 'Phil Sampson and Olly Williams',
        writer: 'Phil Sampson and Olly Williams',
        producer: "Phil Sampson and Olly Williams",
        cast: ['Napoleon Ryan'],
        year: 2008,
        cover: 'https://m.media-amazon.com/images/M/MV5BMTUxNjIwNjMtNDQ2NS00NDFhLWFiNjctYTUyNjgwMTk3OTUxXkEyXkFqcGc@._V1_.jpg',
        url: 'https://www.youtube.com/embed/P5_Msrdg3Hk',
        synopsis: "A sleep-deprived office worker accidentally discovers a black hole - and then greed gets the better of him.."
    },
    {
        name: 'The Sky',
        duration: 11,
        director: 'Matt Sears',
        writer: 'Ryan Grundy',
        producer: "",
        cast: ['Chloe Fox', 'Charlotte Christof'],
        year: 2017,
        cover: 'https://i.ytimg.com/vi/ln4lDjT8Ab0/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDE1j9qkjvcRaFNOfY3us0DoiD84A',
        url: 'https://www.youtube.com/embed/ln4lDjT8Ab0',
        synopsis: "As the world commences its end, a young runaway must figure out if she has chosen the right person to spend her final moments with."
    },
    {
        name: 'My first day',
        duration: 1,
        director: 'Jon Kovel',
        writer: 'Jon Kovel',
        producer: "Brandon Hall",
        cast: ['Reiley Cook'],
        year: 2017,
        cover: 'https://s1.dmcdn.net/v/MrD0Q1QF3eUVUZ2Ie/x1080',
        url: 'https://www.youtube.com/embed/209Sx07OPnU',
        synopsis: "Who isn’t excited on their first day of school?"
    },
    {
        name: 'Lights Out',
        duration: 2,
        director: 'David Sandberg',
        writer: 'David Sandberg',
        producer: "David Sandberg",
        cast: ['Lotta Losten'],
        year: 2013,
        cover: 'https://m.media-amazon.com/images/M/MV5BNjYwMTY5MTgxOF5BMl5BanBnXkFtZTgwOTAyODgxOTE@._V1_.jpg',
        url: 'https://www.youtube.com/embed/FUQhNGEu2KA',
        synopsis: "Something is wrong at home; don't turn off the lights."
    },
    {
        name: 'Make me a sandwich',
        duration: 3,
        director: 'Denman Hatch',
        writer: '',
        producer: "Peter Hatch, Matt Hamilton and Kerry-lee Finkle",
        cast: ['Anne Shepherd', 'Peter Hodgins'],
        year: null,
        cover: 'https://www.indieshortsmag.com/wp-content/uploads/2020/03/Make-Me-a-Sandwich-Short-Film-Review-Indie-Shorts-Mag-2.jpg',
        url: 'https://www.youtube.com/embed/pfGEdmZyVyY&t=8s',
        synopsis: "Marcy, a wife traumatized by her abusive husband, makes him a sandwich every time he yells at her for one."
    },
    {
        name: 'Curve',
        duration: 9,
        director: 'Tim Egan',
        writer: 'Tim Egan',
        producer: "Ahren Morris",
        cast: ['Laura Jane Turner'],
        year: 2016,
        cover: '//static.shortoftheweek.com/wp-content/uploads/2017/06/CURVE_HERO_1.jpg',
        url: 'https://www.youtube.com/embed/2dD3Fawk4y0',
        synopsis: "The shortfilm centers on a young woman who finds herself trapped on a curved, slippery surface with no apparent way to escape."
    },
    {
        name: 'Closing time',
        duration: 7,
        director: 'Spencer Keller',
        writer: 'Spencer Keller',
        producer: "Raymond Power, Noah Lang, Hannah May Keller",
        cast: ['Adata Toop', "Hailey Stubblefield", 'Raymond Power'],
        year: 2024,
        cover: 'https://m.media-amazon.com/images/M/MV5BNjBiNjk1MTgtZDhjNi00ZTUzLTk3Y2YtZGMwNDYwZGFmZDhjXkEyXkFqcGc@._V1_.jpg',
        url: 'https://www.youtube.com/embed/xm6NjBngIx0',
        synopsis: "Emma has something important to tell her boyfriend, but when she arrives to meet him at the local diner and he's missing, she has a gut feeling that something is wrong."
    },
    {
        name: '2AM: The Smiling Man',
        duration: 4,
        director: 'Michael Evans',
        writer: 'Shun Otsubo',
        producer: "Michael Evans",
        cast: ['Sean Simon', "Paul Foltz"],
        year: 2013,
        cover: 'https://m.media-amazon.com/images/M/MV5BNTdjZTJlYjktZDlkZS00NzBjLTg2NTktMmY4N2IwNDI4MjIyXkEyXkFqcGdeQXVyNDE5MTU2MDE@._V1_.jpg',
        url: 'https://www.youtube.com/embed/_u6Tt3PqIfQ',
        synopsis: "A stranger with a sinister smile keeps following you down the street at night."
    },
    {
        name: 'The Jigsaw',
        duration: 8,
        director: 'Basil and Rashad Al-Safar',
        writer: 'Basil and Rashad Al-Safar',
        producer: "Basil and Rashad Al-Safar",
        cast: ['Pedro Monteiro', "Daragh 0'Malley"],
        year: 2017,
        cover: 'https://m.media-amazon.com/images/M/MV5BMDNlNjBhZjYtZDAyZS00NmM2LThiMWUtNjgwN2MwYTgyMWVkXkEyXkFqcGdeQXVyNDE5MTU2MDE@._V1_.jpg',
        url: 'https://www.youtube.com/embed/gs5zQBBOXrA',
        synopsis: "A man buys a puzzle in an old shop; the last piece will bring a great surprise."
    },
    {
        name: 'Peephole',
        duration: 3,
        director: 'Jaron Henrie-Mccrea',
        writer: 'Jaron Henrie-Mccrea',
        producer: "Carys Edwards",
        cast: ['Tim Lueke'],
        year: 2018,
        cover: 'https://m.media-amazon.com/images/M/MV5BZGVhNjRjMjYtY2ViZC00NTJkLWIxZTMtZjhlNmE1NTA2ZGMwXkEyXkFqcGdeQXVyNDA1NDYxNA@@._V1_.jpg',
        url: 'https://www.youtube.com/embed/dKcOTr7N4lE',
        synopsis: "A man answers a knock at the door."
    },
    {
        name: 'The Dollmaker',
        duration: 9,
        director: 'Al Lougher',
        writer: 'Matias Caruso',
        producer: "Richard D'Angelo, Chloe Na",
        cast: ['Perri Lauren', 'Sean Meehan', 'Dan Berkey', 'Tony Hutaj', 'Carlon Jeffery'],
        year: 2017,
        cover: 'https://m.media-amazon.com/images/M/MV5BMjQ3N2M1OWMtNDJjZC00NjM3LTg2YWMtZmQ2YWMyZDJjMGY3XkEyXkFqcGdeQXVyMzQ2NTQyMjA@._V1_.jpg',
        url: 'https://www.youtube.com/embed/XdmefxcnL38',
        synopsis: "A couple's sanity spirals out of control as they come into the possession of a doll that acts as a magical surrogate for their lost child."
    },
    {
        name: 'The Strange Thing About The Johnsons',
        duration: 29,
        director: 'Ari Aster',
        writer: 'Ari Aster',
        producer: 'Alejandro de Leon',
        cast: ['Billy Mayo', 'Brandon Greenhouse', 'Angela Bullock', 'Danielle Watts', 'Carlon Jeffery'],
        year: 2011,
        cover: 'https://m.media-amazon.com/images/M/MV5BNmIyYmU1YjItNjAyMS00YThlLTk3OTktNjZiNWIwNzE3ZDA3XkEyXkFqcGdeQXVyMTEzNzczMA@@._V1_.jpg',
        url: 'https://www.youtube.com/embed/taj2BwNSq18?t=228s',
        synopsis: 'It follows the disturbing story of the Johnson family, focusing on the dark and unsettling dynamics between a father and his son.'
    }
]